steps:
  # Build the landing container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/landing-service:latest", "."]

  # Push the landing container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/landing-service:latest"]

  # Deploy landing to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "landing-service"
      - "--image=gcr.io/$PROJECT_ID/landing-service:latest"
      - "--region=us-central1"
      - "--platform=managed"
      - "--allow-unauthenticated"
